### ISSUE TITLE
New fixture Ecoparcan-1815 -RGBWA+UV

### ISSUE THREAD

**Issue by susobaco** [mcallegari/qlcplus-extras#7]
Greetings, I'm trying to make a fixture for this led par, but, sorry, I'm a rookie and I think I'm not doing well. Can someone help me? Thank you

http://www.acson.com/pdf/DataSheets/ELAN/ECOPARCAN-1815-RGBWA.pdf

[Ecoparcan-1815.qxf.zip](https://github.com/mcallegari/qlcplus-extras/files/3058939/Ecoparcan-1815.qxf.zip)

**Comment by mcallegari** [comment]
This is not the right place to request for support.
Pelase use the dedicated forum area: https://www.qlcplus.org/forum/viewforum.php?f=6
